# Generated by Django 6.0.4 on 2026-05-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='book_images/')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], default='Available', max_length=20)),
            ],
        ),
    ]
