# Generated by Django 6.0.4 on 2026-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
