# Generated by Django 6.0.4 on 2026-05-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_login_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
