# Generated by Django 6.0.4 on 2026-05-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('trending', 'Trending'), ('coding', 'Coding'), ('novels', 'Novels')], default='trending', max_length=20),
        ),
    ]
