# Generated by Django 6.0.4 on 2026-05-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_book_category'),
        ('pages', '0007_profile_address'),
    ]

    operations = [
    ]
