# Generated by Django 6.0.4 on 2026-05-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
